# Generated by Django 3.2.1 on 2021-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelimit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcescore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='资源ID'),
        ),
    ]
