# Generated by Django 3.2.1 on 2021-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210516_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcescore',
            name='source_img',
            field=models.ImageField(blank=True, default='sources/images/default.png', null=True, upload_to='sources/images/2021051714280515', verbose_name='资源图片'),
        ),
    ]
