# Generated by Django 3.2.1 on 2021-05-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
