# Generated by Django 3.2.1 on 2021-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
